micronaut:
  application:
    name: JavaCommon
  server:
    port: 8083
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  prometheus:
    sensitive: false